{{- if and .Values.observability.prometheus.enabled .Values.observability.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pistonprotection.fullname" . }}
  labels:
    {{- include "pistonprotection.labels" . | nindent 4 }}
  {{- if .Values.observability.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.observability.prometheus.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pistonprotection.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.observability.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.observability.prometheus.serviceMonitor.scrapeTimeout }}
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
